# These are supported funding model platforms

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://buymeacoffee.com/mvddonk
  - https://www.paypal.com/donate/?business=4TULNJZAN6P62&no_recurring=0&item_name=Keeping+the+Brewfather+integration+going%21%0Ahttps%3A%2F%2Fgithub.com%2FMvdDonk%2Fbrewfather&currency_code=EUR
