# Brewfather Temperature Sync Automation
# Automatically adjusts your fermentation chamber to match the target temperature from Brewfather recipe
# Simple and reliable - updates when target temperature changes

alias: Brewfather - Sync Fermentation Temperature
description: Automatically sync fermentation chamber temperature with Brewfather recipe target
mode: single

triggers:
  # When Brewfather target temperature changes
  - entity_id: sensor.brewfather_target_temperature
    id: new_temperature
    trigger: state
  
  # Safety: Turn off if sensor becomes unavailable for 5 minutes
  - entity_id: sensor.brewfather_target_temperature
    id: unavailable_temperature
    to: unavailable
    for:
      minutes: 5
    trigger: state

actions:
  - if:
      - condition: trigger
        id: new_temperature
    then:
      # Set fermentation chamber to the new target temperature
      - action: climate.set_temperature
        data:
          temperature: "{{ states('sensor.brewfather_target_temperature') }}"
        target:
          entity_id: climate.fermentation_chamber
    else:
      # Optional: Turn off climate control if sensor unavailable
      # Uncomment the lines below if you want to turn off when unavailable
      # - action: climate.turn_off
      #   target:
      #     entity_id: climate.fermentation_chamber
